# Generated by Django 3.0.7 on 2021-04-29 18:03

from django.db import migrations, models
import django.db.models.deletion
import policyengine.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('policyengine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordCommunity',
            fields=[
                ('community_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='policyengine.Community')),
                ('team_id', models.CharField(max_length=150, unique=True, verbose_name='team_id')),
                ('access_token', models.CharField(max_length=300, unique=True, verbose_name='access_token')),
                ('refresh_token', models.CharField(max_length=500, null=True, verbose_name='refresh_token')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('policyengine.community',),
        ),
        migrations.CreateModel(
            name='DiscordPostMessage',
            fields=[
                ('platformaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='policyengine.PlatformAction')),
                ('text', models.TextField()),
                ('channel', models.CharField(choices=[('733209360549019691', 'general'), ('733982247014891530', 'test')], max_length=18)),
            ],
            options={
                'permissions': (('can_execute_discordpostmessage', 'Can execute discord post message'),),
            },
            bases=('policyengine.platformaction',),
        ),
        migrations.CreateModel(
            name='DiscordRenameChannel',
            fields=[
                ('platformaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='policyengine.PlatformAction')),
                ('channel', models.CharField(choices=[('733209360549019691', 'general'), ('733982247014891530', 'test')], max_length=18)),
                ('name', models.TextField()),
            ],
            options={
                'permissions': (('can_execute_discordrenamechannel', 'Can execute discord rename channel'),),
            },
            bases=('policyengine.platformaction',),
        ),
        migrations.CreateModel(
            name='DiscordStarterKit',
            fields=[
                ('starterkit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='policyengine.StarterKit')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('policyengine.starterkit',),
        ),
        migrations.CreateModel(
            name='DiscordUser',
            fields=[
                ('communityuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='policyengine.CommunityUser')),
                ('refresh_token', models.CharField(max_length=500, null=True, verbose_name='refresh_token')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('policyengine.communityuser',),
            managers=[
                ('objects', policyengine.models.PolymorphicUserManager()),
            ],
        ),
    ]
