# Generated by Django 3.2.2 on 2021-09-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild_id', models.BigIntegerField()),
                ('channel_id', models.BigIntegerField()),
                ('channel_name', models.TextField()),
            ],
        ),
    ]
