# Generated by Django 3.0.7 on 2021-05-08 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policyengine', '0001_initial'),
        ('discord', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild_id', models.IntegerField()),
                ('channel_id', models.IntegerField()),
                ('channel_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DiscordCreateChannel',
            fields=[
                ('platformaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='policyengine.PlatformAction')),
                ('guild_id', models.IntegerField()),
                ('channel_id', models.IntegerField(blank=True)),
                ('name', models.TextField()),
            ],
            options={
                'permissions': (('can_execute_discordcreatechannel', 'Can execute discord create channel'),),
            },
            bases=('policyengine.platformaction',),
        ),
        migrations.CreateModel(
            name='DiscordDeleteChannel',
            fields=[
                ('platformaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='policyengine.PlatformAction')),
                ('channel_id', models.IntegerField()),
            ],
            options={
                'permissions': (('can_execute_discorddeletechannel', 'Can execute discord delete channel'),),
            },
            bases=('policyengine.platformaction',),
        ),
        migrations.CreateModel(
            name='DiscordDeleteMessage',
            fields=[
                ('platformaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='policyengine.PlatformAction')),
                ('channel_id', models.IntegerField()),
                ('message_id', models.IntegerField()),
                ('text', models.TextField(blank=True, default='')),
            ],
            options={
                'permissions': (('can_execute_discorddeletemessage', 'Can execute discord delete message'),),
            },
            bases=('policyengine.platformaction',),
        ),
        migrations.RemoveField(
            model_name='discordcommunity',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='discordcommunity',
            name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='discordpostmessage',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='discordrenamechannel',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='discorduser',
            name='refresh_token',
        ),
        migrations.AddField(
            model_name='discordpostmessage',
            name='channel_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discordpostmessage',
            name='message_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discordrenamechannel',
            name='channel_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discordrenamechannel',
            name='name_old',
            field=models.TextField(blank=True, default=''),
        ),
    ]
