# Generated by Django 3.2.2 on 2021-12-14 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policyengine', '0007_rename_event_data_webhooktriggeraction_data'),
        ('discord', '0002_discordcommunity_discordcreatechannel_discorddeletechannel_discorddeletemessage_discordpostmessage_d'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordSlashCommand',
            fields=[
                ('baseaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='policyengine.baseaction')),
                ('channel', models.BigIntegerField()),
                ('value', models.TextField()),
                ('interaction_token', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
            bases=('policyengine.baseaction', models.Model),
        ),
        migrations.DeleteModel(
            name='DiscordChannel',
        ),
        migrations.RemoveField(
            model_name='discorddeletechannel',
            name='governableaction_ptr',
        ),
        migrations.RemoveField(
            model_name='discorddeletemessage',
            name='governableaction_ptr',
        ),
        migrations.RemoveField(
            model_name='discordpostmessage',
            name='governableaction_ptr',
        ),
        migrations.RemoveField(
            model_name='discordrenamechannel',
            name='governableaction_ptr',
        ),
        migrations.DeleteModel(
            name='DiscordCreateChannel',
        ),
        migrations.DeleteModel(
            name='DiscordDeleteChannel',
        ),
        migrations.DeleteModel(
            name='DiscordDeleteMessage',
        ),
        migrations.DeleteModel(
            name='DiscordPostMessage',
        ),
        migrations.DeleteModel(
            name='DiscordRenameChannel',
        ),
    ]
