# Generated by Django 3.2.2 on 2021-07-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0002_discordcommunity_discordcreatechannel_discorddeletechannel_discorddeletemessage_discordpostmessage_d'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discordcreatechannel',
            name='guild_id',
        ),
        migrations.AlterField(
            model_name='discordchannel',
            name='channel_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='discordchannel',
            name='guild_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='discordcreatechannel',
            name='channel_id',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='discorddeletechannel',
            name='channel_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='discorddeletemessage',
            name='channel_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='discorddeletemessage',
            name='message_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='discordpostmessage',
            name='channel_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='discordpostmessage',
            name='message_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='discordrenamechannel',
            name='channel_id',
            field=models.BigIntegerField(),
        ),
    ]
