# Generated by Django 3.2.2 on 2021-08-16 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policyengine', '0010_auto_20210816_1800'),
        ('discord', '0003_auto_20210713_1548'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscordStarterKit',
        ),
    ]
