# Generated by Django 3.2.2 on 2021-08-04 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0003_auto_20210713_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discordstarterkit',
            name='starterkit_ptr',
        ),
    ]
