# Generated by Django 3.2.2 on 2021-08-04 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0004_remove_discordstarterkit_starterkit_ptr'),
        ('policyengine', '0010_auto_20210804_1749'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscordStarterKit',
        ),
    ]
