# Generated by Django 3.2.2 on 2021-08-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policyengine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='governance_process_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
