# Generated by Django 3.2.2 on 2023-06-07 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policyengine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedure',
            name='fail',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='success',
        ),
    ]
