# Generated by Django 3.2.2 on 2021-09-09 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policyengine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutedActionTriggerAction',
            fields=[
                ('baseaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='policyengine.baseaction')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policyengine.governableaction')),
            ],
            options={
                'abstract': False,
            },
            bases=('policyengine.baseaction', models.Model),
        ),
    ]
