# Generated by Django 3.2.2 on 2021-08-08 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policyengine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communityrole',
            options={},
        ),
        migrations.AlterModelOptions(
            name='constitutionaction',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='constitutionactionbundle',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='platformaction',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='platformactionbundle',
            options={'base_manager_name': 'objects'},
        ),
    ]
