# Generated by Django 3.2.2 on 2021-08-09 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policyengine', '0002_auto_20210808_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policyevaluation',
            old_name='proposal_time',
            new_name='created_at',
        ),
    ]
