# Generated by Django 3.2.2 on 2021-06-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policyengine', '0002_policy_recovery'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaCommunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metagov_slug', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
