# Generated by Django 3.2.2 on 2021-07-22 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metagov', '0003_auto_20210720_2102'),
        ('policyengine', '0002_proposal_governance_process_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlatformPolicy',
            new_name='BasePolicy',
        ),
        migrations.RemoveField(
            model_name='constitutionpolicybundle',
            name='bundled_policies',
        ),
        migrations.RemoveField(
            model_name='constitutionpolicybundle',
            name='community',
        ),
        migrations.RemoveField(
            model_name='constitutionpolicybundle',
            name='data',
        ),
        migrations.RemoveField(
            model_name='platformpolicybundle',
            name='bundled_policies',
        ),
        migrations.RemoveField(
            model_name='platformpolicybundle',
            name='community',
        ),
        migrations.RemoveField(
            model_name='platformpolicybundle',
            name='data',
        ),
        migrations.CreateModel(
            name='PlatformPolicy',
            fields=[
            ],
            options={
                'verbose_name': 'platformpolicy',
                'verbose_name_plural': 'platformpolicies',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('policyengine.basepolicy',),
        ),
        migrations.AlterModelOptions(
            name='basepolicy',
            options={},
        ),
        migrations.DeleteModel(
            name='ConstitutionPolicy',
        ),
        migrations.DeleteModel(
            name='ConstitutionPolicyBundle',
        ),
        migrations.DeleteModel(
            name='PlatformPolicyBundle',
        ),
        migrations.CreateModel(
            name='ConstitutionPolicy',
            fields=[
            ],
            options={
                'verbose_name': 'constitutionpolicy',
                'verbose_name_plural': 'constitutionpolicies',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('policyengine.basepolicy',),
        ),
        migrations.CreateModel(
            name='ConstitutionPolicyBundle',
            fields=[
            ],
            options={
                'verbose_name': 'constitutionpolicybundle',
                'verbose_name_plural': 'constitutionpolicybundles',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('policyengine.basepolicy',),
        ),
        migrations.CreateModel(
            name='PlatformPolicyBundle',
            fields=[
            ],
            options={
                'verbose_name': 'platformpolicybundle',
                'verbose_name_plural': 'platformpolicybundles',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('policyengine.basepolicy',),
        ),
    ]
