# Generated by Django 3.2.2 on 2023-07-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policyengine', '0002_auto_20230607_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtermodule',
            name='data',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
