# Generated by Django 3.2.2 on 2021-07-22 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policyengine', '0003_auto_20210722_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policykitchangeplatformpolicy',
            name='platform_policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policyengine.platformpolicy'),
        ),
        migrations.AlterField(
            model_name='policykitrecoverplatformpolicy',
            name='platform_policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='policyengine.platformpolicy'),
        ),
        migrations.AlterField(
            model_name='policykitremoveplatformpolicy',
            name='platform_policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='policyengine.platformpolicy'),
        ),
    ]
