# Generated by Django 3.2.2 on 2021-06-08 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policyengine', '0003_metacommunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='meta_community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='policyengine.metacommunity'),
        ),
    ]
