# Generated by Django 3.2.2 on 2023-07-16 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policyengine', '0003_filtermodule_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtermodule',
            name='prompt',
            field=models.TextField(blank=True, default=''),
        ),
    ]
