# Generated by Django 3.2.2 on 2021-07-23 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metagov', '0004_alter_metagovprocess_policy'),
        ('policyengine', '0003_base_policy_migration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlatformPolicy',
        ),
    ]
