# Generated by Django 3.2.2 on 2021-08-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policyengine', '0003_rename_proposal_time_policyevaluation_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyevaluation',
            name='community_post',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
