# Generated by Django 3.2.2 on 2021-08-09 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policyengine', '0004_policyevaluation_community_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseaction',
            name='community_post',
        ),
    ]
