# Generated by Django 3.2.2 on 2021-06-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policyengine', '0004_community_meta_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metacommunity',
            name='metagov_slug',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
