# Generated by Django 3.2.2 on 2024-11-06 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policyengine', '0004_filtermodule_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='policy_template',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy', to='policyengine.policytemplate'),
        ),
    ]
