# Generated by Django 3.2.2 on 2021-07-22 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policyengine', '0004_auto_20210722_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='basepolicy',
            name='bundled_policies',
            field=models.ManyToManyField(blank=True, related_name='member_of_bundle', to='policyengine.BasePolicy'),
        ),
    ]
