# Generated by Django 3.2.2 on 2021-11-10 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211101_2053'),
        ('policyengine', '0004_webhooktriggeraction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='governance_process_json',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='governance_process_url',
        ),
        migrations.AddField(
            model_name='proposal',
            name='governance_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.governanceprocess'),
        ),
    ]
