# Generated by Django 3.2.2 on 2021-07-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policyengine', '0004_delete_platformpolicy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='name',
            field=models.CharField(default='Unnamed Policy', max_length=100),
            preserve_default=False,
        ),
    ]
