# Generated by Django 3.2.2 on 2021-07-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policyengine', '0005_alter_policy_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editormodel',
            name='name',
            field=models.CharField(default='Unnamed Policy', max_length=100),
            preserve_default=False,
        ),
    ]
