# Generated by Django 3.2.2 on 2021-07-22 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policyengine', '0005_basepolicy_bundled_policies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basepolicy',
            name='is_bundled',
        ),
    ]
