# Generated by Django 3.2.2 on 2021-11-16 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policyengine', '0005_auto_20211110_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webhooktriggeraction',
            old_name='json_data',
            new_name='event_data',
        ),
    ]
