# Generated by Django 3.2.2 on 2021-08-09 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_db_logger', '0003_rename_evaluation_evaluationlog_proposal'),
        ('policyengine', '0005_remove_baseaction_community_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PolicyEvaluation',
            new_name='Proposal',
        ),
        migrations.RenameField(
            model_name='booleanvote',
            old_name='evaluation',
            new_name='proposal',
        ),
        migrations.RenameField(
            model_name='numbervote',
            old_name='evaluation',
            new_name='proposal',
        ),
    ]
