# Generated by Django 3.2.2 on 2021-11-16 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policyengine', '0006_rename_json_data_webhooktriggeraction_event_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webhooktriggeraction',
            old_name='event_data',
            new_name='data',
        ),
    ]
