# Generated by Django 3.2.2 on 2021-06-08 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policyengine', '0006_alter_metacommunity_metagov_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metacommunity',
            name='metagov_slug',
        ),
    ]
