# Generated by Django 3.2.2 on 2021-08-09 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policyengine', '0006_auto_20210809_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='created_at',
            new_name='proposal_time',
        ),
    ]
