# Generated by Django 3.2.2 on 2021-07-23 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policyengine', '0006_alter_editormodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editormodel',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(limit_value=1, message='Name is required')]),
        ),
        migrations.AlterField(
            model_name='policy',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(limit_value=1, message='Name is required')]),
        ),
    ]
