# Generated by Django 3.2.2 on 2021-07-23 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policyengine', '0007_basepolicy_kind'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConstitutionPolicy',
        ),
        migrations.DeleteModel(
            name='ConstitutionPolicyBundle',
        ),
        migrations.DeleteModel(
            name='PlatformPolicy',
        ),
        migrations.DeleteModel(
            name='PlatformPolicyBundle',
        ),
        migrations.AlterField(
            model_name='policykitchangeconstitutionpolicy',
            name='constitution_policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policyengine.basepolicy'),
        ),
        migrations.AlterField(
            model_name='policykitchangeplatformpolicy',
            name='platform_policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policyengine.basepolicy'),
        ),
        migrations.AlterField(
            model_name='policykitrecoverconstitutionpolicy',
            name='constitution_policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='policyengine.basepolicy'),
        ),
        migrations.AlterField(
            model_name='policykitrecoverplatformpolicy',
            name='platform_policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='policyengine.basepolicy'),
        ),
        migrations.AlterField(
            model_name='policykitremoveconstitutionpolicy',
            name='constitution_policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='policyengine.basepolicy'),
        ),
        migrations.AlterField(
            model_name='policykitremoveplatformpolicy',
            name='platform_policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='policyengine.basepolicy'),
        ),
    ]
