# Generated by Django 3.2.2 on 2021-07-23 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policyengine', '0007_auto_20210723_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constitutionaction',
            name='data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='policyengine.datastore', verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='constitutionactionbundle',
            name='data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='policyengine.datastore', verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='editormodel',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='platformaction',
            name='data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='policyengine.datastore', verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='platformactionbundle',
            name='data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='policyengine.datastore', verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='policyengine.datastore', verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
