# Generated by Django 3.2.2 on 2021-12-17 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policyengine', '0007_rename_event_data_webhooktriggeraction_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='community_post',
            new_name='vote_post_id',
        ),
    ]
