# Generated by Django 3.2.2 on 2021-12-29 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policyengine', '0008_rename_community_post_proposal_vote_post_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GovernableActionBundle',
        ),
    ]
