# Generated by Django 3.2.2 on 2021-08-03 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policyengine', '0008_auto_20210723_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='author',
        ),
    ]
