# Generated by Django 3.2.2 on 2022-03-28 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policyengine', '0009_delete_governableactionbundle'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseaction',
            name='data_store',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='policyengine.datastore'),
        ),
    ]
