# Generated by Django 3.2.2 on 2021-08-16 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('policyengine', '0009_remove_proposal_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GenericPolicy',
        ),
        migrations.DeleteModel(
            name='GenericRole',
        ),
    ]
