# Generated by Django 3.2.2 on 2022-10-16 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policyengine', '0010_baseaction_data_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policy',
            name='variables',
            field=models.JSONField(null=True, verbose_name='PolicyVariables'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='policyengine.community'),
        ),
    ]
