# Generated by Django 3.2.2 on 2021-08-04 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0005_delete_discordstarterkit'),
        ('policyengine', '0010_auto_20210804_1749'),
        ('discourse', '0003_delete_discoursestarterkit'),
        ('reddit', '0002_delete_redditstarterkit'),
        ('slack', '0004_delete_slackstarterkit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StarterKit',
        ),
    ]
