# Generated by Django 3.2.2 on 2022-09-22 15:00

from django.db import migrations, models
import django.db.models.deletion
import policyengine.models


class Migration(migrations.Migration):

    dependencies = [
        ('policyengine', '0010_baseaction_data_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_kind', models.CharField(choices=[('platform', 'platform'), ('constitution', 'constitution'), ('trigger', 'trigger')], max_length=30)),
                ('template_filter', models.TextField(blank=True, default='')),
                ('template_initialize', models.TextField(blank=True, default='')),
                ('template_check', models.TextField(blank=True, default='')),
                ('template_notify', models.TextField(blank=True, default='')),
                ('template_success', models.TextField(blank=True, default='')),
                ('template_fail', models.TextField(blank=True, default='')),
                ('template_name', models.CharField(max_length=100)),
                ('template_description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('template_variables', models.JSONField(default=policyengine.models.PolicyTemplate.variables_default, verbose_name='TemplateVariables')),
                ('template_action_types', models.ManyToManyField(to='policyengine.ActionType')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyTemplateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.JSONField(default=policyengine.models.PolicyTemplateData.values_default, verbose_name='PolicyTemplateValues')),
                ('policy', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='policyengine.policy')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policyengine.policytemplate')),
            ],
        ),
        migrations.AddField(
            model_name='policy',
            name='source_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='policyengine.policytemplate'),
        ),
    ]
