# Generated by Django 3.2.2 on 2022-11-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policyengine', '0012_auto_20221017_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyvariable',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
    ]
