# Generated by Django 3.2.2 on 2022-12-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policyengine', '0015_auto_20221120_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
    ]
