# Generated by Django 3.2.2 on 2022-12-12 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policyengine', '0016_policy_is_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='policyengine.community'),
        ),
    ]
