# Generated by Django 3.2.2 on 2023-03-09 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policyengine', '0017_alter_policy_community'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='')),
                ('initial_code', models.TextField(blank=True, default='')),
                ('notify_code', models.TextField(blank=True, default='')),
                ('check_code', models.TextField(blank=True, default='')),
                ('variables_dict', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='policyengine.governableaction')),
            ],
        ),
        migrations.CreateModel(
            name='CustomAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter', models.TextField(blank=True, default='')),
                ('community_name', models.TextField(null=True, unique=True)),
                ('is_user_generated', models.BooleanField(default=False)),
                ('is_trigger', models.BooleanField(default=False)),
                ('action_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policyengine.actiontype')),
            ],
        ),
    ]
