# Generated by Django 3.2.2 on 2023-03-09 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policyengine', '0018_customaction_execution_procedure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedure',
            old_name='initial_code',
            new_name='initialize_code',
        ),
    ]
