# Generated by Django 3.2.2 on 2023-05-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policyengine', '0018_auto_20230504_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transformer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='', unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('codes', models.TextField(blank=True, default='')),
                ('variables', models.TextField(blank=True, default='[]')),
                ('data', models.TextField(blank=True, default='[]')),
            ],
        ),
        migrations.DeleteModel(
            name='CheckModule',
        ),
        migrations.RemoveField(
            model_name='policytemplate',
            name='extra_check',
        ),
        migrations.AddField(
            model_name='policytemplate',
            name='transformers',
            field=models.ManyToManyField(to='policyengine.Transformer'),
        ),
    ]
