# Generated by Django 3.2.2 on 2024-08-27 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policyengine', '0018_auto_20230521_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policytemplate',
            old_name='extra_executions',
            new_name='executions',
        ),
        migrations.RemoveField(
            model_name='customaction',
            name='is_trigger',
        ),
        migrations.RemoveField(
            model_name='policytemplate',
            name='is_trigger',
        ),
        migrations.RemoveField(
            model_name='policytemplate',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='fail',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='success',
        ),
        migrations.AddField(
            model_name='filtermodule',
            name='data',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='filtermodule',
            name='prompt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='policytemplate',
            name='template_kind',
            field=models.CharField(choices=[('if_then_rules', 'if_then_rules'), ('community_policies', 'community_policies'), ('triggering_policies', 'triggering_policies')], default='community_policies', max_length=30),
        ),
        migrations.CreateModel(
            name='SelectVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_time', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.CharField(max_length=100)),
                ('option', models.CharField(max_length=100)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policyengine.proposal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policyengine.communityuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
