# Generated by Django 3.2.2 on 2023-03-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policyengine', '0019_rename_initial_code_procedure_initialize_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
