# Generated by Django 3.2.25 on 2025-03-31 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policyengine', '0022_policy_policy_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='policytemplate',
            name='custom_action_code',
            field=models.TextField(blank=True, default=''),
        ),
    ]
