# Generated by Django 3.2.25 on 2025-04-05 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policyengine', '0022_policy_policy_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customaction',
            name='action_type',
        ),
        migrations.AddField(
            model_name='customaction',
            name='action_types',
            field=models.ManyToManyField(related_name='custom_actions', to='policyengine.ActionType'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='is_template',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='procedure',
            name='view',
            field=models.CharField(choices=[('codes', 'codes'), ('form', 'form')], default='form', max_length=10),
        ),
        migrations.AddField(
            model_name='transformer',
            name='is_template',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customaction',
            name='filter',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='check',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='initialize',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterUniqueTogether(
            name='procedure',
            unique_together=set(),
        ),
    ]
