# Generated by Django 3.2.25 on 2025-03-31 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policyengine', '0023_policytemplate_custom_action_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customaction',
            name='action_type',
        ),
        migrations.RemoveField(
            model_name='policytemplate',
            name='custom_action_code',
        ),
        migrations.AddField(
            model_name='customaction',
            name='action_types',
            field=models.ManyToManyField(related_name='custom_actions', to='policyengine.ActionType'),
        ),
    ]
