# Generated by Django 3.2.25 on 2025-04-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policyengine', '0023_auto_20250405_0305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policytemplate',
            name='transformers',
        ),
        migrations.AddField(
            model_name='procedure',
            name='transformers',
            field=models.ManyToManyField(to='policyengine.Transformer'),
        ),
    ]
