# Generated by Django 3.0.7 on 2021-04-29 18:03

from django.db import migrations, models
import django.db.models.deletion
import policyengine.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('policyengine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackCommunity',
            fields=[
                ('community_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='policyengine.Community')),
                ('team_id', models.CharField(max_length=150, unique=True, verbose_name='team_id')),
                ('access_token', models.CharField(max_length=300, unique=True, verbose_name='access_token')),
                ('bot_id', models.CharField(default='', max_length=150, unique=True, verbose_name='bot_id')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('policyengine.community',),
        ),
        migrations.CreateModel(
            name='SlackJoinConversation',
            fields=[
                ('platformaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='policyengine.PlatformAction')),
                ('channel', models.CharField(max_length=150, verbose_name='channel')),
                ('users', models.CharField(max_length=15, verbose_name='users')),
            ],
            options={
                'permissions': (('can_execute_slackjoinconversation', 'Can execute slack join conversation'),),
            },
            bases=('policyengine.platformaction',),
        ),
        migrations.CreateModel(
            name='SlackKickConversation',
            fields=[
                ('platformaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='policyengine.PlatformAction')),
                ('user', models.CharField(max_length=15, verbose_name='user')),
                ('channel', models.CharField(max_length=150, verbose_name='channel')),
            ],
            options={
                'permissions': (('can_execute_slackkickconversation', 'Can execute slack kick conversation'),),
            },
            bases=('policyengine.platformaction',),
        ),
        migrations.CreateModel(
            name='SlackPinMessage',
            fields=[
                ('platformaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='policyengine.PlatformAction')),
                ('channel', models.CharField(max_length=150, verbose_name='channel')),
                ('timestamp', models.CharField(max_length=150, verbose_name='timestamp')),
            ],
            options={
                'permissions': (('can_execute_slackpinmessage', 'Can execute slack pin message'),),
            },
            bases=('policyengine.platformaction',),
        ),
        migrations.CreateModel(
            name='SlackPostMessage',
            fields=[
                ('platformaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='policyengine.PlatformAction')),
                ('text', models.TextField()),
                ('channel', models.CharField(max_length=150, verbose_name='channel')),
            ],
            options={
                'permissions': (('can_execute_slackpostmessage', 'Can execute slack post message'),),
            },
            bases=('policyengine.platformaction',),
        ),
        migrations.CreateModel(
            name='SlackRenameConversation',
            fields=[
                ('platformaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='policyengine.PlatformAction')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('channel', models.CharField(max_length=150, verbose_name='channel')),
            ],
            options={
                'permissions': (('can_execute_slackrenameconversation', 'Can execute slack rename conversation'),),
            },
            bases=('policyengine.platformaction',),
        ),
        migrations.CreateModel(
            name='SlackScheduleMessage',
            fields=[
                ('platformaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='policyengine.PlatformAction')),
                ('text', models.TextField()),
                ('channel', models.CharField(max_length=150, verbose_name='channel')),
                ('post_at', models.IntegerField(verbose_name='post at')),
            ],
            options={
                'permissions': (('can_execute_slackschedulemessage', 'Can execute slack schedule message'),),
            },
            bases=('policyengine.platformaction',),
        ),
        migrations.CreateModel(
            name='SlackStarterKit',
            fields=[
                ('starterkit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='policyengine.StarterKit')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('policyengine.starterkit',),
        ),
        migrations.CreateModel(
            name='SlackUser',
            fields=[
                ('communityuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='policyengine.CommunityUser')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('policyengine.communityuser',),
            managers=[
                ('objects', policyengine.models.PolymorphicUserManager()),
            ],
        ),
    ]
