# Generated by Django 3.2.2 on 2021-08-08 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slackkickconversation',
            options={'permissions': (('can_execute_slackkickconversation', 'Can execute slack kick conversation'),), 'verbose_name': 'remove user from slack conversation'},
        ),
    ]
