# Generated by Django 3.2.2 on 2021-06-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackpostmessage',
            name='timestamp',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='slackpinmessage',
            name='timestamp',
            field=models.CharField(max_length=32),
        ),
    ]
