# Generated by Django 3.2.2 on 2021-06-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0002_auto_20210615_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackrenameconversation',
            name='previous_name',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
    ]
