# Generated by Django 3.2.2 on 2021-08-16 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policyengine', '0010_auto_20210816_1800'),
        ('slack', '0003_slackrenameconversation_previous_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SlackStarterKit',
        ),
    ]
