# Generated by Django 3.2.2 on 2021-06-15 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_db_logger', '0001_initial'),
        ('policyengine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationlog',
            name='community',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='policyengine.communityplatform'),
        ),
    ]
