# Generated by Django 3.2.2 on 2021-08-04 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policyengine', '0010_auto_20210804_1749'),
        ('reddit', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RedditStarterKit',
        ),
    ]
