# Generated by Django 3.2.2 on 2021-09-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constitution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policykitaddconstitutionpolicy',
            name='check',
            field=models.TextField(blank=True, verbose_name='Check'),
        ),
        migrations.AlterField(
            model_name='policykitaddconstitutionpolicy',
            name='fail',
            field=models.TextField(blank=True, verbose_name='Fail'),
        ),
        migrations.AlterField(
            model_name='policykitaddconstitutionpolicy',
            name='filter',
            field=models.TextField(blank=True, verbose_name='Filter'),
        ),
        migrations.AlterField(
            model_name='policykitaddconstitutionpolicy',
            name='initialize',
            field=models.TextField(blank=True, verbose_name='Initialize'),
        ),
        migrations.AlterField(
            model_name='policykitaddconstitutionpolicy',
            name='notify',
            field=models.TextField(blank=True, verbose_name='Notify'),
        ),
        migrations.AlterField(
            model_name='policykitaddconstitutionpolicy',
            name='success',
            field=models.TextField(blank=True, verbose_name='Pass'),
        ),
        migrations.AlterField(
            model_name='policykitaddplatformpolicy',
            name='check',
            field=models.TextField(blank=True, verbose_name='Check'),
        ),
        migrations.AlterField(
            model_name='policykitaddplatformpolicy',
            name='fail',
            field=models.TextField(blank=True, verbose_name='Fail'),
        ),
        migrations.AlterField(
            model_name='policykitaddplatformpolicy',
            name='filter',
            field=models.TextField(blank=True, verbose_name='Filter'),
        ),
        migrations.AlterField(
            model_name='policykitaddplatformpolicy',
            name='initialize',
            field=models.TextField(blank=True, verbose_name='Initialize'),
        ),
        migrations.AlterField(
            model_name='policykitaddplatformpolicy',
            name='notify',
            field=models.TextField(blank=True, verbose_name='Notify'),
        ),
        migrations.AlterField(
            model_name='policykitaddplatformpolicy',
            name='success',
            field=models.TextField(blank=True, verbose_name='Pass'),
        ),
        migrations.AlterField(
            model_name='policykitaddtriggerpolicy',
            name='check',
            field=models.TextField(blank=True, verbose_name='Check'),
        ),
        migrations.AlterField(
            model_name='policykitaddtriggerpolicy',
            name='fail',
            field=models.TextField(blank=True, verbose_name='Fail'),
        ),
        migrations.AlterField(
            model_name='policykitaddtriggerpolicy',
            name='filter',
            field=models.TextField(blank=True, verbose_name='Filter'),
        ),
        migrations.AlterField(
            model_name='policykitaddtriggerpolicy',
            name='initialize',
            field=models.TextField(blank=True, verbose_name='Initialize'),
        ),
        migrations.AlterField(
            model_name='policykitaddtriggerpolicy',
            name='notify',
            field=models.TextField(blank=True, verbose_name='Notify'),
        ),
        migrations.AlterField(
            model_name='policykitaddtriggerpolicy',
            name='success',
            field=models.TextField(blank=True, verbose_name='Pass'),
        ),
        migrations.AlterField(
            model_name='policykitchangeconstitutionpolicy',
            name='check',
            field=models.TextField(blank=True, verbose_name='Check'),
        ),
        migrations.AlterField(
            model_name='policykitchangeconstitutionpolicy',
            name='fail',
            field=models.TextField(blank=True, verbose_name='Fail'),
        ),
        migrations.AlterField(
            model_name='policykitchangeconstitutionpolicy',
            name='filter',
            field=models.TextField(blank=True, verbose_name='Filter'),
        ),
        migrations.AlterField(
            model_name='policykitchangeconstitutionpolicy',
            name='initialize',
            field=models.TextField(blank=True, verbose_name='Initialize'),
        ),
        migrations.AlterField(
            model_name='policykitchangeconstitutionpolicy',
            name='notify',
            field=models.TextField(blank=True, verbose_name='Notify'),
        ),
        migrations.AlterField(
            model_name='policykitchangeconstitutionpolicy',
            name='success',
            field=models.TextField(blank=True, verbose_name='Pass'),
        ),
        migrations.AlterField(
            model_name='policykitchangeplatformpolicy',
            name='check',
            field=models.TextField(blank=True, verbose_name='Check'),
        ),
        migrations.AlterField(
            model_name='policykitchangeplatformpolicy',
            name='fail',
            field=models.TextField(blank=True, verbose_name='Fail'),
        ),
        migrations.AlterField(
            model_name='policykitchangeplatformpolicy',
            name='filter',
            field=models.TextField(blank=True, verbose_name='Filter'),
        ),
        migrations.AlterField(
            model_name='policykitchangeplatformpolicy',
            name='initialize',
            field=models.TextField(blank=True, verbose_name='Initialize'),
        ),
        migrations.AlterField(
            model_name='policykitchangeplatformpolicy',
            name='notify',
            field=models.TextField(blank=True, verbose_name='Notify'),
        ),
        migrations.AlterField(
            model_name='policykitchangeplatformpolicy',
            name='success',
            field=models.TextField(blank=True, verbose_name='Pass'),
        ),
        migrations.AlterField(
            model_name='policykitchangetriggerpolicy',
            name='check',
            field=models.TextField(blank=True, verbose_name='Check'),
        ),
        migrations.AlterField(
            model_name='policykitchangetriggerpolicy',
            name='fail',
            field=models.TextField(blank=True, verbose_name='Fail'),
        ),
        migrations.AlterField(
            model_name='policykitchangetriggerpolicy',
            name='filter',
            field=models.TextField(blank=True, verbose_name='Filter'),
        ),
        migrations.AlterField(
            model_name='policykitchangetriggerpolicy',
            name='initialize',
            field=models.TextField(blank=True, verbose_name='Initialize'),
        ),
        migrations.AlterField(
            model_name='policykitchangetriggerpolicy',
            name='notify',
            field=models.TextField(blank=True, verbose_name='Notify'),
        ),
        migrations.AlterField(
            model_name='policykitchangetriggerpolicy',
            name='success',
            field=models.TextField(blank=True, verbose_name='Pass'),
        ),
    ]
