# Generated by Django 3.2.2 on 2021-12-16 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policyengine', '0007_rename_event_data_webhooktriggeraction_data'),
        ('constitution', '0003_policykitaddintegration_policykitremoveintegration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policykitadduserrole',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='policyengine.communityrole'),
        ),
        migrations.AlterField(
            model_name='policykitremoveuserrole',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='policyengine.communityrole'),
        ),
    ]
