# Generated by Django 3.2.2 on 2022-11-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policyengine', '0012_auto_20221017_1721'),
        ('constitution', '0004_auto_20211216_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='policykitaddconstitutionpolicy',
            name='variables',
            field=models.ManyToManyField(to='policyengine.PolicyVariable'),
        ),
        migrations.AddField(
            model_name='policykitaddplatformpolicy',
            name='variables',
            field=models.ManyToManyField(to='policyengine.PolicyVariable'),
        ),
        migrations.AddField(
            model_name='policykitaddtriggerpolicy',
            name='variables',
            field=models.ManyToManyField(to='policyengine.PolicyVariable'),
        ),
        migrations.AddField(
            model_name='policykitchangeconstitutionpolicy',
            name='variables',
            field=models.ManyToManyField(to='policyengine.PolicyVariable'),
        ),
        migrations.AddField(
            model_name='policykitchangeplatformpolicy',
            name='variables',
            field=models.ManyToManyField(to='policyengine.PolicyVariable'),
        ),
        migrations.AddField(
            model_name='policykitchangetriggerpolicy',
            name='variables',
            field=models.ManyToManyField(to='policyengine.PolicyVariable'),
        ),
    ]
