# Generated by Django 3.2.2 on 2022-11-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constitution', '0005_auto_20221112_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policykitaddconstitutionpolicy',
            name='variables',
        ),
        migrations.AddField(
            model_name='policykitaddconstitutionpolicy',
            name='variables',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='policykitaddplatformpolicy',
            name='variables',
        ),
        migrations.AddField(
            model_name='policykitaddplatformpolicy',
            name='variables',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='policykitaddtriggerpolicy',
            name='variables',
        ),
        migrations.AddField(
            model_name='policykitaddtriggerpolicy',
            name='variables',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='policykitchangeconstitutionpolicy',
            name='variables',
        ),
        migrations.AddField(
            model_name='policykitchangeconstitutionpolicy',
            name='variables',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='policykitchangeplatformpolicy',
            name='variables',
        ),
        migrations.AddField(
            model_name='policykitchangeplatformpolicy',
            name='variables',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='policykitchangetriggerpolicy',
            name='variables',
        ),
        migrations.AddField(
            model_name='policykitchangetriggerpolicy',
            name='variables',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
