# Generated by Django 3.0.7 on 2021-04-29 18:03

from django.db import migrations, models
import django.db.models.deletion
import policyengine.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metagov', '0001_initial'),
        ('policyengine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetagovPlatformAction',
            fields=[
                ('platformaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='policyengine.PlatformAction')),
                ('json_data', models.CharField(blank=True, max_length=500, null=True)),
                ('event_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('policyengine.platformaction',),
        ),
        migrations.CreateModel(
            name='MetagovUser',
            fields=[
                ('communityuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='policyengine.CommunityUser')),
                ('provider', models.CharField(help_text='Identity provider that the username comes from', max_length=30)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('policyengine.communityuser',),
            managers=[
                ('objects', policyengine.models.PolymorphicUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MetagovProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=100)),
                ('json_data', models.CharField(blank=True, max_length=500, null=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policyengine.PlatformAction')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policyengine.PlatformPolicy')),
            ],
            options={
                'unique_together': {('policy', 'action')},
            },
        ),
    ]
