# Generated by Django 3.2.2 on 2021-08-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metagov', '0002_metagovaction_metagovuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metagovaction',
            name='json_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
