# Generated by Django 3.2.2 on 2021-09-02 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('policyengine', '0001_initial'),
        ('metagov', '0002_metagovaction_metagovuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MetagovAction',
            new_name='MetagovTrigger',
        ),
    ]
