# Generated by Django 3.2.2 on 2021-08-08 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('policyengine', '0002_auto_20210808_1621'),
        ('metagov', '0002_metagovplatformaction_metagovuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MetagovPlatformAction',
            new_name='MetagovAction',
        ),
    ]
