# Generated by Django 3.2.2 on 2021-07-22 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policyengine', '0004_auto_20210722_2328'),
        ('metagov', '0003_auto_20210720_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metagovprocess',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policyengine.platformpolicy'),
        ),
    ]
