# Generated by Django 3.2.2 on 2021-07-23 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policyengine', '0003_auto_20210723_1448'),
        ('metagov', '0003_auto_20210720_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metagovprocess',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policyengine.basepolicy'),
        ),
    ]
