# Generated by Django 3.2.2 on 2021-07-23 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policyengine', '0008_auto_20210723_1446'),
        ('metagov', '0004_alter_metagovprocess_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metagovprocess',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policyengine.basepolicy'),
        ),
    ]
