# Generated by Django 3.2.2 on 2021-08-04 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discourse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discoursestarterkit',
            name='starterkit_ptr',
        ),
    ]
