# Generated by Django 3.2.2 on 2021-10-12 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policyengine', '0002_executedactiontriggeraction'),
        ('opencollective', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseDeleted',
            fields=[
                ('baseaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='policyengine.baseaction')),
                ('json_data', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
            bases=('policyengine.baseaction', models.Model),
        ),
        migrations.CreateModel(
            name='ExpensePaid',
            fields=[
                ('baseaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='policyengine.baseaction')),
                ('json_data', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
            bases=('policyengine.baseaction', models.Model),
        ),
        migrations.CreateModel(
            name='ExpenseUnapproved',
            fields=[
                ('baseaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='policyengine.baseaction')),
                ('json_data', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
            bases=('policyengine.baseaction', models.Model),
        ),
    ]
