# Generated by Django 3.2.2 on 2021-11-16 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opencollective', '0003_auto_20211116_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenseapproved',
            old_name='raw_data',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='expensecreated',
            old_name='raw_data',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='expensedeleted',
            old_name='raw_data',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='expensepaid',
            old_name='raw_data',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='expenserejected',
            old_name='raw_data',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='expenseunapproved',
            old_name='raw_data',
            new_name='data',
        ),
    ]
