# Generated by Django 3.2.2 on 2023-05-24 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policyengine', '0018_auto_20230521_1821'),
        ('opencollective', '0004_auto_20211116_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenCollectivePostMessage',
            fields=[
                ('baseaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='policyengine.baseaction')),
                ('text', models.TextField()),
                ('expense_id', models.CharField(max_length=150, verbose_name='expense_id')),
            ],
            options={
                'permissions': (('can_execute_opencollectivepostmessage', 'Can execute open collective post message'),),
            },
            bases=('policyengine.baseaction',),
        ),
        migrations.CreateModel(
            name='OpenCollectiveProcessExpense',
            fields=[
                ('baseaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='policyengine.baseaction')),
                ('expense_id', models.CharField(max_length=150, verbose_name='expense_id')),
                ('action', models.CharField(max_length=150, verbose_name='action')),
            ],
            options={
                'permissions': (('can_execute_opencollectiveprocessexpense', 'Can execute open collective process expense'),),
            },
            bases=('policyengine.baseaction',),
        ),
    ]
