"""
Django settings for policykit project.

Generated by 'django-admin startproject' using Django 3.0.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

PRIVATE_FILE_PATH = os.environ.get("PRIVATE_FILE_PATH", BASE_DIR + "/private.py")
try:
    exec(open(PRIVATE_FILE_PATH).read())
except IOError:
    raise Exception(f"Unable to open configuration file at: '{PRIVATE_FILE_PATH}'")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'kg=&9zrc5@rern2=&+6yvh8ip0u7$f=k_zax**bwsur_z7qy+-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['policykit.org',
                 'www.policykit.org',
                 'ec2-52-41-245-161.us-west-2.compute.amazonaws.com',
                 '52.41.245.161',
                 '127.0.0.1',
                 'ec2-54-190-197-117.us-west-2.compute.amazonaws.com',
                 '54.190.197.117',
                 'localhost']

try:
    METAGOV_ENABLED = True if METAGOV_URL else False
except NameError:
    # "METAGOV_URL" is missing from private.py
    METAGOV_ENABLED = False

# Application definition
INTEGRATIONS = [
    'integrations.slack',
    'integrations.reddit',
    'integrations.discord',
    'integrations.discourse',
    'integrations.metagov'
]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.sites',
    'django.contrib.staticfiles',
    'django_celery_beat',
    'django_celery_results',
    'django_filters',
    'django_tables2',
    'django_db_logger',
    'actstream',
    'policyengine',
] + INTEGRATIONS

SITE_ID = 1

ACTSTREAM_SETTINGS = {
    'MANAGER': 'policyengine.managers.myActionManager',
    'FETCH_RELATIONS': True,
    'USE_PREFETCH': True,
    'USE_JSONFIELD': True,
    'GFK_FETCH_DEPTH': 1,
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'policykit.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.template.context_processors.tz',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'policykit.wsgi.application'
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    },

}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


AUTHENTICATION_BACKENDS = ['integrations.discourse.auth_backends.DiscourseBackend',
                           'integrations.discord.auth_backends.DiscordBackend',
                           'integrations.reddit.auth_backends.RedditBackend',
                           'integrations.slack.auth_backends.SlackBackend',
                           'django.contrib.auth.backends.ModelBackend']


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

PROJECT_NAME = "PolicyKit"


### Logging
import sys
import os

# Set default log level
DEFAULT_LOG_LEVEL_FOR_TESTS = "DEBUG"
DEFAULT_LOG_LEVEL = "DEBUG"

TESTING = sys.argv[1:2] == ["test"]
LOG_LEVEL = DEFAULT_LOG_LEVEL_FOR_TESTS if TESTING else DEFAULT_LOG_LEVEL

# Generate loggers for engine and integrations
loggers = {}
for app in ['policyengine'] + INTEGRATIONS:
    loggers.update({app: {"handlers": ["console", "file"], "level": LOG_LEVEL, "propagate": False}})
# Database logger for policy evaluation logs
loggers["db"] = {"handlers": ["db_log"], "level": DEFAULT_LOG_LEVEL, "propagate": True}
# Set log level to WARN for everything else (imported dependencies)
loggers[""] = {"handlers": ["console", "file"], "level": "WARN"}

# Override for specific apps
# loggers['integrations.reddit'] = {'handlers': ['console', 'file'], 'level': "DEBUG"}

# Delete db log records from database after a certain number of hours:
DB_LOG_EXPIRATION_HOURS = 1

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        "console": {"format": "%(name)-12s %(levelname)-8s %(message)s"},
        "file": {"format": "%(asctime)s %(name)-12s %(levelname)-8s %(message)s"},
    },
    'handlers': {
        "db_log": {
            'class': 'django_db_logger.db_log_handler.DatabaseLogHandler'
        },
        "file": {
            "class": "logging.FileHandler",
            "filename": os.environ.get('POLICYKIT_LOG_FILE', "/var/log/django/debug.log"),
            "formatter": "file",
        },
        "console": {"class": "logging.StreamHandler", "formatter": "console"},
    },
    'loggers': loggers
}

from celery.schedules import crontab

# Replace with "amqp://USERNAME:PASSWORD@localhost:5672/VIRTUALHOST"
CELERY_BROKER_URL = 'amqp://'
CELERY_RESULT_BACKEND = 'django-db'
CELERY_CACHE_BACKEND = 'django-cache'

CELERY_BEAT_FREQUENCY = 60.0

CELERY_BEAT_SCHEDULE = {
 'count-votes-beat': {
       'task': 'policyengine.tasks.consider_proposed_actions',
       'schedule': CELERY_BEAT_FREQUENCY,
    },
 'reddit-listener-beat': {
       'task': 'integrations.reddit.tasks.reddit_listener_actions',
       'schedule': CELERY_BEAT_FREQUENCY,
    },
 'discourse-listener-beat': {
       'task': 'integrations.discourse.tasks.discourse_listener_actions',
       'schedule': CELERY_BEAT_FREQUENCY,
    }
}
