# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: PolicyKit Django application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Checkout PolicyKit repository
      uses: actions/checkout@v2
    - name: Install PolicyKit dependencies
      working-directory: ./policykit
      run: |
        pip install --upgrade pip
        pip install -U pip setuptools
        pip install -r requirements.txt
    - name: Run PolicyKit unit tests
      working-directory: ./policykit
      run: |
        python manage.py test
